name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: pipx install poetry==1.8.2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
      - run: poetry install
      - run: poetry run black --check .
      - run: poetry run mypy --check .
