name: Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: pipx install poetry==1.8.2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - run: poetry install
      - name: Build and publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
